---
- name: Verifica se o arquivo do Wordpress já existe em '/tmp/wordpress.tar.gz'
  command: ls /tmp/wordpress.tar.gz
  register: existeWP

- name: 'Baixa o tar.gz do Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
  when: not  existeWP

- name: 'Descompactar o arquivo .tar.gz do Wordpress'
  unarchive: 
    remote_src: yes
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
  become: yes

- name: 'Copia configuracao de exemplo do wordpress'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Altera variaveis do wp-config.php'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_username }}"}
    - { regex: 'password_here', value: "{{ wp_user_password }}"}
    - { regex: 'localhost', value: "{{ wp_db_ip }}"}
  become: yes

- name: Configura Apache para servir o Wordpress
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify:
    - restart apache